DROP TABLE IF EXISTS Patient CASCADE;
DROP TABLE IF EXISTS Medecin CASCADE;
DROP TABLE IF EXISTS RDV CASCADE;

CREATE TABLE Patient (
  email VARCHAR(50) PRIMARY KEY,
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  mdp text NOT NULL,
  telephone VARCHAR(50) NOT NULL
);

CREATE TABLE Medecin (
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  telephone VARCHAR(50) NOT NULL,
  email VARCHAR(50) PRIMARY KEY,
  codepostal VARCHAR(50) NOT NULL,
  mdp text NOT NULL,
  specialite VARCHAR(50)
 );

CREATE TABLE RDV (
  medecinemail VARCHAR(50) NOT NULL,
  patientemail VARCHAR(50) NOT NULL,
  id SERIAL PRIMARY KEY,
  libre BOOL NOT NULL,
  informations TEXT NOT NULL,
  debut TIMESTAMP NOT NULL,
  fin TIMESTAMP NOT NULL,
  FOREIGN KEY(medecinemail) REFERENCES Medecin(email)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(patientemail) REFERENCES Patient(email)
    ON UPDATE CASCADE ON DELETE CASCADE
);
